BASE_CONFIG:
  BASE_URL: http://localhost:3000
  BASE_API_HOST: http://localhost:3000
  BASE_API_VERSION: v1
FEISHU_CONFIG:
  BASE_URL: https://open.feishu.cn/open-apis
  API_HOST: https://open.feishu.cn
  APP_ID: cli_a6880edf257c9013
  APP_SECRET: ikEPPsiDYHT8DOki6Aco0hmK0ChHlI5y
TEST_VALUE:
  name: cookie
